#!/usr/bin/env bash
# gen-shims.sh -- generate libopencm3 shim headers for a shared library
#
# Usage: gen-shims.sh <shared-lib-root>
#
# Automatically discovers all peripherals, their guard defines, and their
# common headers by inspecting the libopencm3 source in the submodule.
# Nothing is hardcoded -- adding a new peripheral to libopencm3 will be
# picked up automatically on the next run.
#
# To upgrade a version: just re-run this script. It re-generates everything
# from the current state of the submodule.

set -euo pipefail

SHARED_ROOT="${1:-}"
if [ -z "$SHARED_ROOT" ]; then
    echo "Usage: gen-shims.sh <shared-lib-root>"
    exit 1
fi

OCM3_INC="$SHARED_ROOT/submodules/libopencm3/include"
DISPATCH_DIR="$OCM3_INC/libopencm3/stm32"
SHIMS_DIR="$SHARED_ROOT/shims"

if [ ! -d "$OCM3_INC" ]; then
    echo "ERROR: libopencm3 submodule not found at $OCM3_INC"
    echo "       Run: git submodule add https://github.com/libopencm3/libopencm3.git submodules/libopencm3"
    exit 1
fi

mkdir -p "$SHIMS_DIR/libopencm3/stm32"

for dispatch in "$DISPATCH_DIR"/*.h; do
    peripheral="$(basename "$dispatch" .h)"

    # Skip non-peripheral headers
    case "$peripheral" in
        memorymap|tools) continue ;;
    esac

    # Step 1: find all family-specific headers this dispatch includes
    family_headers="$(grep -o 'libopencm3/stm32/[a-z0-9]*/[a-z0-9_]*.h' "$dispatch" 2>/dev/null || true)"

    if [ -z "$family_headers" ]; then
        continue
    fi

    # Step 2: for each family header, find which common/ headers it includes
    common_headers=""
    for fam_hdr in $family_headers; do
        fam_path="$OCM3_INC/$fam_hdr"
        [ -f "$fam_path" ] || continue
        found="$(grep -o 'libopencm3/stm32/common/[a-z0-9_]*.h' "$fam_path" 2>/dev/null || true)"
        common_headers="$common_headers $found"
    done

    if [ -z "$common_headers" ]; then
        continue
    fi

    # Step 3: deduplicate, preserving first-seen order
    unique_commons=""
    for h in $common_headers; do
        case " $unique_commons " in
            *" $h "*) ;;
            *) unique_commons="$unique_commons $h" ;;
        esac
    done
    unique_commons="${unique_commons# }"

    # Step 4: find the guard define from the first common header that has one
    guard=""
    for common in $unique_commons; do
        common_path="$OCM3_INC/$common"
        [ -f "$common_path" ] || continue
        found_guard="$(grep -m1 '#ifdef LIBOPENCM3_' "$common_path" 2>/dev/null \
            | sed 's/#ifdef //' | tr -d ' \t\r' || true)"
        if [ -n "$found_guard" ]; then
            guard="$found_guard"
            break
        fi
    done

    # Step 5: write the shim
    out="$SHIMS_DIR/libopencm3/stm32/${peripheral}.h"
    {
        echo "#pragma once"
        echo ""
        echo "/*"
        echo " * Shim for libopencm3/stm32/${peripheral}.h"
        echo " *"
        echo " * Allows shared code to write:"
        echo " *   #include <libopencm3/stm32/${peripheral}.h>"
        echo " * without needing an MCU family define."
        echo " *"
        echo " * When compiled inside an app (MCU define present), this file is"
        echo " * never found -- the app's own libopencm3 dispatch header is used."
        echo " *"
        echo " * Auto-generated by gen-shims.sh -- re-run to update."
        echo " */"
        echo ""
        echo "#include <libopencm3/stm32/memorymap.h>"
        echo "#include <libopencm3/cm3/common.h>"
        if [ -n "$guard" ]; then
            echo "#define ${guard}"
        fi
        for common in $unique_commons; do
            echo "#include <${common}>"
        done
    } > "$out"

    echo "  created: shims/libopencm3/stm32/${peripheral}.h"
done

echo ""
echo "v  Shims written to: $SHIMS_DIR"